### ISSUE TITLE
Still having problem with 1.3.1

### ISSUE THREAD

**Issue by ltd** [bitgapp/Cursr#9]
### Describe the Bug/Issue
Unexpected Error on startup

### Expected Behavior

**Screenshots**

### Your Environment
 - Mac OS
 - Cursr Version 1.3.1

### Additional Context

error_log
2021-08-09T23:40:41.730Z [critical] SyntaxError: Unexpected token  in JSON at position 550
    at JSON.parse (<anonymous>)
    at CursrNative.<anonymous> (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/index.js:31:29)
    at Generator.next (<anonymous>)
    at /Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/index.js:4:12)
    at CursrNative.getDisplays (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/index.js:28:16)
    at Displays.<anonymous> (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:123:59)
    at Generator.next (<anonymous>)
    at /Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:8:71

conf.json
{
  "firstUse": false,
  "setups": [],
  "clientId": "d6ed0cc8-fc86-4870-b871-9eb7cce47a10",
  "runOnStartup": true,
  "autoUpdate": true,
  "window": {
    "position": {
      "x": 628,
      "y": 25
    },
    "size": {
      "width": 650,
      "height": 450
    }
  }
}

**Comment by ragauskl** [comment]
Gotcha, will have a look as soon as I'll be able to, currently on road with car malfunctioning, in best case I'll have it checked out today, in worst if I'll get stuck in day or two

**Comment by ragauskl** [comment]
@ltd I've released v1.3.2, could you let me know if the issue is still happening?

If the issue is still happening, send error log again, I've updated logging as well which will provide more information on the issue

**Comment by ltd** [comment]
here's what I get with 1.3.2
<img width="652" alt="Notification_Center" src="https://user-images.githubusercontent.com/67152/130008143-d31094ec-0a00-4ed8-a51c-4aee72e28cf8.png">

logs/error.log

2021-08-19T04:29:13.070Z [critical] SyntaxError: Failed to parse displays information. Unexpected token x in JSON at position 890 while parsing near '...: "ACI","serial": "\x16","primary": fals...'
    at JSON.parse (<anonymous>)
    at parseJson (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/json-parse-better-errors/index.js:7:17)
    at CursrNative.getDisplays (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/index.js:20:24)
    at Displays.getDisplays (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:124:49)
    at Displays.<anonymous> (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:196:39)
    at Generator.next (<anonymous>)
    at /Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:4:12)
    at Displays.reloadDisplaysData (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:194:16)
2021-08-19T04:29:13.463Z [critical] SyntaxError: Failed to parse displays information. Unexpected token x in JSON at position 1126 while parsing near '...: "ACI","serial": "\x16","primary": fals...'
    at JSON.parse (<anonymous>)
    at parseJson (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/json-parse-better-errors/index.js:7:17)
    at CursrNative.getDisplays (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/index.js:20:24)
    at Displays.getDisplays (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:124:49)
    at Displays.getDisplayFromPixel (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:641:31)
    at AppState.setPosition (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/app-state.js:431:46)
    at AppState.savePosition (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/app-state.js:422:14)
    at SafeSubscriber._next (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/app-state.js:69:50)
    at SafeSubscriber.__tryOrUnsub (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/rxjs/internal/Subscriber.js:143:22)
2021-08-19T04:30:43.299Z [critical] SyntaxError: Failed to parse displays information. Unexpected token x in JSON at position 1122 while parsing near '...: "ACI","serial": "\x16","primary": fals...'
    at JSON.parse (<anonymous>)
    at parseJson (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/json-parse-better-errors/index.js:7:17)
    at CursrNative.getDisplays (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/index.js:20:24)
    at Displays.getDisplays (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:124:49)
    at Displays.<anonymous> (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:196:39)
    at Generator.next (<anonymous>)
    at /Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:4:12)
    at Displays.reloadDisplaysData (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:194:16)
2021-08-19T04:30:47.573Z [critical] SyntaxError: Failed to parse displays information. Unexpected token x in JSON at position 1323 while parsing near '...: "ACI","serial": "\x16","primary": fals...'
    at JSON.parse (<anonymous>)
    at parseJson (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/node_modules/json-parse-better-errors/index.js:7:17)
    at CursrNative.getDisplays (/Applications/Cursr.app/Contents/Resources/app.asar/node_modules/@cursr/native/dist/index.js:20:24)
    at Displays.getDisplays (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:124:49)
    at Displays.<anonymous> (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:196:39)
    at Generator.next (<anonymous>)
    at /Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:4:12)
    at Displays.reloadDisplaysData (/Applications/Cursr.app/Contents/Resources/app.asar/dist/controllers/displays.js:194:16)

**Comment by ragauskl** [comment]
Thank you for sending the logs, I've replicated and fixed the issue, got few more things to add to help with other peoples issue and will release v1.3.3 with the fix in couple days

**Comment by ragauskl** [comment]
v1.3.3 is out now, let me know if release fixed the issue or if it is still present

**Comment by ltd** [comment]
1.3.3 seems to be working. thanks!
